# Generated by Django 6.0.7 on 2026-08-04 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MockAPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(default='v1', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD')], default='GET', max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer', 'Bearer'), ('basic', 'Basic'), ('oauth2', 'OAuth2'), ('custom', 'Custom Header')], default='none', max_length=20)),
                ('auth_config', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('query_params', models.JSONField(blank=True, default=list)),
                ('path_params', models.JSONField(blank=True, default=list)),
                ('body_type', models.CharField(default='json', max_length=50)),
                ('body_schema', models.JSONField(blank=True, default=dict)),
                ('body_example', models.JSONField(blank=True, default=dict)),
                ('responses', models.JSONField(blank=True, default=list)),
                ('behavior', models.JSONField(blank=True, default=dict)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('state_mode', models.CharField(choices=[('stateless', 'Stateless'), ('stateful', 'Stateful')], default='stateless', max_length=20)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('active_scenario', models.CharField(default='default', max_length=100)),
                ('scenarios', models.JSONField(blank=True, default=list)),
                ('rate_limit', models.IntegerField(blank=True, null=True)),
                ('cors_enabled', models.BooleanField(default=True)),
                ('cors_config', models.JSONField(blank=True, default=dict)),
                ('custom_response_headers', models.JSONField(blank=True, default=list)),
                ('webhooks', models.JSONField(blank=True, default=list)),
                ('is_deployed', models.BooleanField(default=False)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('request_count_today', models.IntegerField(default=0)),
                ('total_requests', models.IntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apis', to='apis.collection')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Mock API',
                'verbose_name_plural': 'Mock APIs',
                'ordering': ['-updated_at'],
                'unique_together': {('workspace', 'method', 'endpoint', 'version')},
            },
        ),
        migrations.CreateModel(
            name='APIVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='apis.mockapi')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
