# Generated by Django 6.0.7 on 2026-08-04 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
        ('workspaces', '0004_custom_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockapi',
            name='custom_domain',
            field=models.ForeignKey(blank=True, help_text='Serve this endpoint on a verified custom domain. Null = platform default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apis', to='workspaces.workspacedomain'),
        ),
    ]
