# Generated by Django 5.x
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0004_auto_version_unique_endpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockapi",
            name="endpoint_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("list", "List"),
                    ("detail", "Detail"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("action", "Action"),
                ],
                default="action",
                help_text="Semantic shape: list, detail, create, update, delete, or action.",
                max_length=20,
            ),
        ),
    ]
