# Generated by Django 6.1.1 on 2026-09-16 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0005_mockapi_endpoint_type"),
        ("workspaces", "0004_custom_domains"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("path", models.CharField(max_length=500)),
                ("item_template", models.JSONField(blank=True, default=dict)),
                ("id_field", models.CharField(default="id", max_length=64)),
                ("auth_type", models.CharField(default="none", max_length=20)),
                ("auth_config", models.JSONField(blank=True, default=dict)),
                ("behavior", models.JSONField(blank=True, default=dict)),
                ("allow_writes", models.BooleanField(default=True)),
                ("is_deployed", models.BooleanField(default=True)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("total_requests", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="apis.collection",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("workspace", "path")},
            },
        ),
        migrations.CreateModel(
            name="ResourceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="apis.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("resource", "key")},
            },
        ),
    ]
