# Generated by Django 6.0.7 on 2026-08-04 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_created_by_workspacevariable_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['domain'],
                'unique_together': {('workspace', 'domain')},
            },
        ),
    ]
