# Generated by Django 6.0.7 on 2026-08-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspace_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspacedomain',
            options={'ordering': ['-is_default', 'domain']},
        ),
        migrations.AlterUniqueTogether(
            name='workspacedomain',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workspacedomain',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacedomain',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacedomain',
            name='verification_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workspacedomain',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='workspacedomain',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
