# Generated by Django 6.0.7 on 2026-08-04 07:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
        ('logs', '0001_initial'),
        ('workspaces', '0002_workspace_created_by_workspacevariable_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('secret', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('method', models.CharField(default='POST', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('raw_body', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Webhook deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='requestlog',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='apis.collection'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='finding',
            field=models.CharField(blank=True, help_text='Matched rule, scenario, or condition that determined the response', max_length=255),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='query_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='response_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='rule_matched',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['collection', '-created_at'], name='logs_reques_collect_897b76_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['status_code'], name='logs_reques_status__01be2b_idx'),
        ),
        migrations.AddField(
            model_name='incomingwebhook',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_webhooks', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='outgoingwebhook',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_webhooks', to='apis.mockapi'),
        ),
        migrations.AddField(
            model_name='outgoingwebhook',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_webhooks', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='webhook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='logs.incomingwebhook'),
        ),
        migrations.AlterUniqueTogether(
            name='incomingwebhook',
            unique_together={('workspace', 'slug')},
        ),
    ]
